#idndef RAM_8_HPP
#define RAM_8_HPP

#include "../bus_8/BUS_8.hpp"
#include "../register_8/REGISTER_8.hpp"


class RAM_8: public COMPONENT{

  //inputs

  //data inputs
  I_BUFFER INPUT_BUFFER_DATA_IN0;
  I_BUFFER INPUT_BUFFER_DATA_IN1;
  I_BUFFER INPUT_BUFFER_DATA_IN2;
  I_BUFFER INPUT_BUFFER_DATA_IN3;
  I_BUFFER INPUT_BUFFER_DATA_IN4;
  I_BUFFER INPUT_BUFFER_DATA_IN5;
  I_BUFFER INPUT_BUFFER_DATA_IN6;
  I_BUFFER INPUT_BUFFER_DATA_IN7;

  //data outputs
  BUFFER OUTPUT_BUFFER_DATA_OUT0;
  BUFFER OUTPUT_BUFFER_DATA_OUT1;
  BUFFER OUTPUT_BUFFER_DATA_OUT2;
  BUFFER OUTPUT_BUFFER_DATA_OUT3;
  BUFFER OUTPUT_BUFFER_DATA_OUT4;
  BUFFER OUTPUT_BUFFER_DATA_OUT5;
  BUFFER OUTPUT_BUFFER_DATA_OUT6;
  BUFFER OUTPUT_BUFFER_DATA_OUT7;

  //memory address (4 registers so 2-bit)
  I_BUFFER INPUT_BUFFER_ADDRESS0;
  I_BUFFER INPUT_BUFFER_ADDRESS1;

  //control inputs
  I_BUFFER INPUT_BUFFER_READ_ENABLE;
  I_BUFFER INPUT_BUFFER_WRITE_ENABLE;

  //clock
  I_BUFFER INPUT_BUFFER_CLK;

  //registers
  REGISTER_8 MEM0;
  REGISTER_8 MEM1;
  REGISTER_8 MEM2;
  REGISTER_8 MEM4;

  //data bus
  BUS_8 DATA_BUS;






}


#endif
